# Copyright 2026 Victor Stewart
# SPDX-License-Identifier: Apache-2.0
if (NOT DEFINED BASICS_PACKAGE_DEPOFILE OR "${BASICS_PACKAGE_DEPOFILE}" STREQUAL "")
  message(FATAL_ERROR "BASICS_PACKAGE_DEPOFILE is required.")
endif()

if (NOT DEFINED EXPECT_TIDESDB OR "${EXPECT_TIDESDB}" STREQUAL "")
  message(FATAL_ERROR "EXPECT_TIDESDB must be ON or OFF.")
endif()

file(READ "${BASICS_PACKAGE_DEPOFILE}" _basics_package_depofile)

string(FIND "${_basics_package_depofile}" "DEPENDS tidesdb VERSION 8.6.2" _basics_tidesdb_depends_index)
string(FIND "${_basics_package_depofile}" "tidesdb::tidesdb" _basics_tidesdb_link_index)
string(FIND "${_basics_package_depofile}" "# tidesdb support: ON" _basics_tidesdb_comment_on_index)
string(FIND "${_basics_package_depofile}" "# tidesdb support: OFF" _basics_tidesdb_comment_off_index)
string(FIND "${_basics_package_depofile}" "STAGE_TREE SOURCE databases include/databases" _basics_tidesdb_stage_index)

if (EXPECT_TIDESDB)
  if (_basics_tidesdb_depends_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to depend on tidesdb.")
  endif()
  if (_basics_tidesdb_link_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to link tidesdb::tidesdb.")
  endif()
  if (_basics_tidesdb_comment_on_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to mark tidesdb support as ON.")
  endif()
  if (_basics_tidesdb_stage_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to stage the databases tree.")
  endif()
else()
  if (NOT _basics_tidesdb_depends_index EQUAL -1)
    message(FATAL_ERROR "Generated basics package depofile unexpectedly depends on tidesdb.")
  endif()
  if (NOT _basics_tidesdb_link_index EQUAL -1)
    message(FATAL_ERROR "Generated basics package depofile unexpectedly links tidesdb::tidesdb.")
  endif()
  if (_basics_tidesdb_comment_off_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to mark tidesdb support as OFF.")
  endif()
  if (NOT _basics_tidesdb_stage_index EQUAL -1)
    message(FATAL_ERROR "Generated basics package depofile unexpectedly stages the optional databases tree.")
  endif()
endif()
