if (NOT DEFINED BASICS_SOURCE_DIR)
  message(FATAL_ERROR "BASICS_SOURCE_DIR is required")
endif()

file(GLOB depofiles "${BASICS_SOURCE_DIR}/depofiles/*.DepoFile")
foreach(depofile IN LISTS depofiles)
  file(STRINGS "${depofile}" lines)
  list(LENGTH lines line_count)
  math(EXPR last_line "${line_count} - 1")
  foreach(index RANGE 0 ${last_line})
    list(GET lines ${index} line)
    if (line MATCHES "^SOURCE URL https://")
      math(EXPR checksum_index "${index} + 1")
      if (checksum_index GREATER_EQUAL line_count)
        message(FATAL_ERROR "${depofile} has no checksum after '${line}'")
      endif()
      list(GET lines ${checksum_index} checksum)
      string(REGEX MATCH "^SHA256 ([0-9a-f]+)$" checksum_match "${checksum}")
      string(LENGTH "${CMAKE_MATCH_1}" checksum_length)
      if (NOT checksum_match OR NOT checksum_length EQUAL 64)
        message(FATAL_ERROR "${depofile} has no exact SHA256 after '${line}'")
      endif()
    endif()
  endforeach()
endforeach()
