# Copyright 2026 Victor Stewart
# SPDX-License-Identifier: Apache-2.0
if (NOT DEFINED BASICS_PACKAGE_DEPOFILE OR "${BASICS_PACKAGE_DEPOFILE}" STREQUAL "")
  message(FATAL_ERROR "BASICS_PACKAGE_DEPOFILE is required.")
endif()

if (NOT DEFINED EXPECT_TIDESDB OR "${EXPECT_TIDESDB}" STREQUAL "")
  message(FATAL_ERROR "EXPECT_TIDESDB must be ON or OFF.")
endif()

file(READ "${BASICS_PACKAGE_DEPOFILE}" _basics_package_depofile)

string(FIND "${_basics_package_depofile}" "DEPENDS tidesdb VERSION 9.3.5" _basics_tidesdb_depends_index)
string(FIND "${_basics_package_depofile}" "tidesdb::tidesdb" _basics_tidesdb_link_index)
string(FIND "${_basics_package_depofile}" "# tidesdb support: ON" _basics_tidesdb_comment_on_index)
string(FIND "${_basics_package_depofile}" "# tidesdb support: OFF" _basics_tidesdb_comment_off_index)
string(FIND "${_basics_package_depofile}" "STAGE_TREE SOURCE databases include/databases" _basics_tidesdb_stage_index)
string(FIND "${_basics_package_depofile}" "DEPENDS aegis VERSION 0.10.1" _basics_aegis_depends_index)
string(FIND "${_basics_package_depofile}" "aegis::aegis" _basics_aegis_link_index)
string(FIND "${_basics_package_depofile}" "DEPENDS libssh2 VERSION 1.11.1" _basics_libssh2_depends_index)
string(FIND "${_basics_package_depofile}" "libssh2::libssh2" _basics_libssh2_link_index)
string(FIND "${_basics_package_depofile}" "DEPENDS liburing VERSION 2.14" _basics_liburing_depends_index)
string(FIND "${_basics_package_depofile}" "liburing::liburing::" _basics_liburing_link_index)
string(FIND "${_basics_package_depofile}" "DEPENDS nghttp2 VERSION 1.69.0" _basics_nghttp2_depends_index)
string(FIND "${_basics_package_depofile}" "nghttp2::nghttp2" _basics_nghttp2_link_index)

foreach(_basics_forbidden_surface_token IN ITEMS
  "DEPENDS libbpf" "DEPENDS libcurl" "DEPENDS simdjson" "DEPENDS zlib"
  "libbpf::" "libcurl::" "simdjson::" "zlib::"
)
  string(FIND "${_basics_package_depofile}" "${_basics_forbidden_surface_token}" _basics_forbidden_surface_index)
  if (NOT _basics_forbidden_surface_index EQUAL -1)
    message(FATAL_ERROR "Generated basics package depofile must not expose optional runtime/client dependency '${_basics_forbidden_surface_token}' through basics::basics.")
  endif()
endforeach()

if (_basics_aegis_depends_index EQUAL -1)
  message(FATAL_ERROR "Generated basics package depofile must depend on aegis because networking/stream.h includes it.")
endif()
if (_basics_aegis_link_index EQUAL -1)
  message(FATAL_ERROR "Generated basics package depofile must link aegis::aegis because networking/stream.h calls it.")
endif()
if (_basics_libssh2_depends_index EQUAL -1)
  message(FATAL_ERROR "Generated basics package depofile must depend on libssh2 because networking/ssh.h includes it.")
endif()
if (_basics_libssh2_link_index EQUAL -1)
  message(FATAL_ERROR "Generated basics package depofile must link libssh2::libssh2 because networking/ssh.h calls it.")
endif()
if (_basics_liburing_depends_index EQUAL -1)
  message(FATAL_ERROR "Generated basics package depofile must depend on liburing because networking/ring.h includes it.")
endif()
if (_basics_liburing_link_index EQUAL -1)
  message(FATAL_ERROR "Generated basics package depofile must link liburing because networking/ring.h calls it.")
endif()
if (_basics_nghttp2_depends_index EQUAL -1)
  message(FATAL_ERROR "Generated basics package depofile must depend on nghttp2 because networking/h2nb.client.h includes it.")
endif()
if (_basics_nghttp2_link_index EQUAL -1)
  message(FATAL_ERROR "Generated basics package depofile must link nghttp2::nghttp2 because networking/h2nb.client.h calls it.")
endif()

if (EXPECT_TIDESDB)
  if (_basics_tidesdb_depends_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to depend on tidesdb.")
  endif()
  if (_basics_tidesdb_link_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to link tidesdb::tidesdb.")
  endif()
  if (_basics_tidesdb_comment_on_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to mark tidesdb support as ON.")
  endif()
  if (_basics_tidesdb_stage_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to stage the databases tree.")
  endif()
else()
  if (NOT _basics_tidesdb_depends_index EQUAL -1)
    message(FATAL_ERROR "Generated basics package depofile unexpectedly depends on tidesdb.")
  endif()
  if (NOT _basics_tidesdb_link_index EQUAL -1)
    message(FATAL_ERROR "Generated basics package depofile unexpectedly links tidesdb::tidesdb.")
  endif()
  if (_basics_tidesdb_comment_off_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to mark tidesdb support as OFF.")
  endif()
  if (NOT _basics_tidesdb_stage_index EQUAL -1)
    message(FATAL_ERROR "Generated basics package depofile unexpectedly stages the optional databases tree.")
  endif()
endif()
