# Copyright 2026 Victor Stewart
# SPDX-License-Identifier: Apache-2.0
if (NOT DEFINED BASICS_PACKAGE_DEPOFILE OR "${BASICS_PACKAGE_DEPOFILE}" STREQUAL "")
  message(FATAL_ERROR "BASICS_PACKAGE_DEPOFILE is required.")
endif()

if (NOT DEFINED EXPECT_TIDESDB OR "${EXPECT_TIDESDB}" STREQUAL "")
  message(FATAL_ERROR "EXPECT_TIDESDB must be ON or OFF.")
endif()

file(READ "${BASICS_PACKAGE_DEPOFILE}" _basics_package_depofile)
get_filename_component(_basics_package_root "${BASICS_PACKAGE_DEPOFILE}" DIRECTORY)
set(_basics_tidesdb_header "${_basics_package_root}/payload/include/databases/embedded/tidesdb.h")

string(FIND "${_basics_package_depofile}" "DEPENDS tidesdb VERSION 8.6.2" _basics_tidesdb_depends_index)
string(FIND "${_basics_package_depofile}" "tidesdb::tidesdb" _basics_tidesdb_link_index)
string(FIND "${_basics_package_depofile}" "# tidesdb support: ON" _basics_tidesdb_comment_on_index)
string(FIND "${_basics_package_depofile}" "# tidesdb support: OFF" _basics_tidesdb_comment_off_index)

if (EXPECT_TIDESDB)
  if (_basics_tidesdb_depends_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to depend on tidesdb.")
  endif()
  if (_basics_tidesdb_link_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to link tidesdb::tidesdb.")
  endif()
  if (_basics_tidesdb_comment_on_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to mark tidesdb support as ON.")
  endif()
  if (NOT EXISTS "${_basics_tidesdb_header}")
    message(FATAL_ERROR "Expected tidesdb header to be staged into the generated basics package payload: ${_basics_tidesdb_header}")
  endif()
else()
  if (NOT _basics_tidesdb_depends_index EQUAL -1)
    message(FATAL_ERROR "Generated basics package depofile unexpectedly depends on tidesdb.")
  endif()
  if (NOT _basics_tidesdb_link_index EQUAL -1)
    message(FATAL_ERROR "Generated basics package depofile unexpectedly links tidesdb::tidesdb.")
  endif()
  if (_basics_tidesdb_comment_off_index EQUAL -1)
    message(FATAL_ERROR "Expected generated basics package depofile to mark tidesdb support as OFF.")
  endif()
  if (EXISTS "${_basics_tidesdb_header}")
    message(FATAL_ERROR "Generated basics package payload unexpectedly staged the optional tidesdb header: ${_basics_tidesdb_header}")
  endif()
endif()
